name: Test and Coverage Check

on:
  push:
    branches:
      - main
      - development

jobs:
  test-and-check-coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21.7'

    - name: Install dependencies and update go.mod/go.sum
      run: |
        go get -t -v ./...
        go mod tidy

    - name: Run tests
      run: |
        go test -cover ./usecases/...

    - name: Check coverage
      run: |
        coverage=$(go test -cover ./usecases/... | grep -o '[0-9.]\+%' | cut -d'.' -f1 | tr -d '%')
    
        if [[ "$coverage" -ge 90 ]]; then
          echo "All services have coverage above 90%, pushing is allowed."
        else
          echo "Some services have coverage below 90%, pushing is aborted."
          exit 1
        fi